#!/bin/sh
# Regenerates api/schema/ from the live database: one file per domain, so the
# layout reads like a model package instead of one long dump. Run from the repo
# root via `just api-schema`.
set -eu

DB="ludus"
OUT="api/schema"
PG="docker compose exec -T postgres"

auth="users user_identities sessions device_authorizations oauth_states"
habits="habits habit_checkins"
plans="plan_levels plan_requirements plan_requirement_habits plan_tasks"
goals="goals task_goals"
teams="teams team_members workflow_states labels cycles"
projects="projects project_members milestones milestone_members"
tasks="tasks task_labels task_relations comments horizons"
meta="__diesel_schema_migrations"

mapped="$auth $habits $plans $goals $teams $projects $tasks $meta"

# A table nobody filed would silently vanish from the dump, so refuse instead.
live=$($PG psql -qAt -U "$DB" -d "$DB" -c "select tablename from pg_tables where schemaname='public' order by tablename")
missing=""
for t in $live; do
    case " $mapped " in *" $t "*) ;; *) missing="$missing $t" ;; esac
done
if [ -n "$missing" ]; then
    echo "dump-schema: unfiled table(s):$missing" >&2
    echo "Add them to a group in $0." >&2
    exit 1
fi

header="-- Generated by \`just api-schema\`. Do not edit: change the database with a migration."

dump() {
    file="$1"
    shift
    args=""
    for t in "$@"; do args="$args -t public.$t"; done
    { echo "$header"; echo
      # shellcheck disable=SC2086
      # Keep the body between the first object and the trailer, which carries a
      # per-run random token and would churn the diff on every regeneration.
      $PG pg_dump -s -U "$DB" --no-owner --no-privileges $args "$DB" \
          | awk '/^-- Name:/ { on = 1 }
                 /^-- PostgreSQL database dump complete/ { exit }
                 on { body[++n] = $0 }
                 END { while (n > 0 && (body[n] == "" || body[n] == "--")) n--
                       for (i = 1; i <= n; i++) print body[i] }' \
          | grep -vE '^(SET |SELECT pg_catalog\.set_config)' \
          | cat -s
    } > "$OUT/$file"
}

rm -rf "$OUT"
mkdir -p "$OUT"

dump auth.sql $auth
dump habits.sql $habits
dump plans.sql $plans
dump goals.sql $goals
dump teams.sql $teams
dump projects.sql $projects
dump tasks.sql $tasks

# Functions have no -t switch, so they are read back individually.
{ echo "$header"; echo
  $PG psql -qAt -U "$DB" -d "$DB" -c \
      "select pg_get_functiondef(p.oid) || ';' from pg_proc p
       join pg_namespace n on n.oid = p.pronamespace
       where n.nspname = 'public' order by p.proname"
} > "$OUT/_functions.sql"

dump _migrations.sql $meta
