-- Generated by `just api-schema`. Do not edit: change the database with a migration.

-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    team_id uuid,
    project_id uuid,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    target_date date,
    "position" double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);

--
-- Name: task_goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_goals (
    task_id uuid NOT NULL,
    goal_id uuid NOT NULL
);

--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);

--
-- Name: task_goals task_goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_goals
    ADD CONSTRAINT task_goals_pkey PRIMARY KEY (task_id, goal_id);

--
-- Name: idx_goals_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goals_project ON public.goals USING btree (project_id);

--
-- Name: idx_goals_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goals_team ON public.goals USING btree (team_id);

--
-- Name: idx_goals_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goals_user ON public.goals USING btree (user_id);

--
-- Name: idx_task_goals_goal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_goals_goal ON public.task_goals USING btree (goal_id);

--
-- Name: goals set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.goals FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: goals goals_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- Name: goals goals_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;

--
-- Name: goals goals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: task_goals task_goals_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_goals
    ADD CONSTRAINT task_goals_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;

--
-- Name: task_goals task_goals_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_goals
    ADD CONSTRAINT task_goals_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;
