-- Generated by `just api-schema`. Do not edit: change the database with a migration.

-- Name: habit_checkins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.habit_checkins (
    habit_id uuid NOT NULL,
    day date NOT NULL,
    times integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT habit_checkins_times_check CHECK ((times > 0))
);

--
-- Name: habits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.habits (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    weekdays smallint[],
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    archived_at timestamp with time zone,
    icon text,
    color text,
    unit text,
    tracking text DEFAULT 'binary'::text NOT NULL,
    "position" double precision NOT NULL,
    goal_id uuid
);

--
-- Name: habit_checkins habit_checkins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habit_checkins
    ADD CONSTRAINT habit_checkins_pkey PRIMARY KEY (habit_id, day) INCLUDE (times);

--
-- Name: habits habits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT habits_pkey PRIMARY KEY (id);

--
-- Name: idx_habits_goal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_habits_goal ON public.habits USING btree (goal_id);

--
-- Name: idx_habits_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_habits_user ON public.habits USING btree (user_id);

--
-- Name: habit_checkins set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.habit_checkins FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: habits set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.habits FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: habit_checkins habit_checkins_habit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habit_checkins
    ADD CONSTRAINT habit_checkins_habit_id_fkey FOREIGN KEY (habit_id) REFERENCES public.habits(id) ON DELETE CASCADE;

--
-- Name: habits habits_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT habits_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE SET NULL;

--
-- Name: habits habits_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT habits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
