-- Generated by `just api-schema`. Do not edit: change the database with a migration.

-- Name: plan_requirement_habits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_requirement_habits (
    requirement_id uuid NOT NULL,
    habit_id uuid NOT NULL
);

--
-- Name: plan_requirement_quotas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_requirement_quotas (
    requirement_id uuid NOT NULL,
    tier_id uuid NOT NULL,
    quota double precision NOT NULL,
    CONSTRAINT plan_requirement_quotas_quota_check CHECK ((quota > (0)::double precision))
);

--
-- Name: plan_requirements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_requirements (
    id uuid NOT NULL,
    plan_id uuid NOT NULL,
    name text,
    measure text DEFAULT 'amount'::text NOT NULL,
    "position" double precision NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    CONSTRAINT plan_requirements_measure_check CHECK ((measure = ANY (ARRAY['amount'::text, 'occurrences'::text]))),
    CONSTRAINT plan_requirements_validity_check CHECK (((valid_to IS NULL) OR (valid_to > valid_from)))
);

--
-- Name: plan_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_tasks (
    plan_id uuid NOT NULL,
    task_id uuid NOT NULL,
    period_start date NOT NULL
);

--
-- Name: plan_tiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_tiers (
    id uuid NOT NULL,
    plan_id uuid NOT NULL,
    name text,
    medal text,
    "position" double precision NOT NULL,
    retired_on date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plan_tiers_medal_check CHECK ((medal = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text])))
);

--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    period text NOT NULL,
    "position" double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    archived_on date,
    CONSTRAINT plans_period_check CHECK ((period = ANY (ARRAY['day'::text, 'week'::text, 'month'::text, 'quarter'::text, 'year'::text])))
);

--
-- Name: plan_requirement_habits plan_requirement_habits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_habits
    ADD CONSTRAINT plan_requirement_habits_pkey PRIMARY KEY (requirement_id, habit_id);

--
-- Name: plan_requirement_quotas plan_requirement_quotas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_quotas
    ADD CONSTRAINT plan_requirement_quotas_pkey PRIMARY KEY (requirement_id, tier_id);

--
-- Name: plan_requirements plan_requirements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirements
    ADD CONSTRAINT plan_requirements_pkey PRIMARY KEY (id);

--
-- Name: plan_tasks plan_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tasks
    ADD CONSTRAINT plan_tasks_pkey PRIMARY KEY (plan_id, task_id, period_start);

--
-- Name: plan_tiers plan_tiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tiers
    ADD CONSTRAINT plan_tiers_pkey PRIMARY KEY (id);

--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);

--
-- Name: plans plans_user_id_period_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_user_id_period_name_key UNIQUE (user_id, period, name);

--
-- Name: idx_plan_requirement_habits_habit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_requirement_habits_habit ON public.plan_requirement_habits USING btree (habit_id);

--
-- Name: idx_plan_requirement_quotas_tier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_requirement_quotas_tier ON public.plan_requirement_quotas USING btree (tier_id);

--
-- Name: idx_plan_requirements_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_requirements_plan ON public.plan_requirements USING btree (plan_id);

--
-- Name: idx_plan_tasks_task; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_tasks_task ON public.plan_tasks USING btree (task_id);

--
-- Name: idx_plan_tiers_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_tiers_plan ON public.plan_tiers USING btree (plan_id);

--
-- Name: idx_plans_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plans_user ON public.plans USING btree (user_id);

--
-- Name: plans set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.plans FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: plan_requirement_habits plan_requirement_habits_habit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_habits
    ADD CONSTRAINT plan_requirement_habits_habit_id_fkey FOREIGN KEY (habit_id) REFERENCES public.habits(id) ON DELETE CASCADE;

--
-- Name: plan_requirement_habits plan_requirement_habits_requirement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_habits
    ADD CONSTRAINT plan_requirement_habits_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.plan_requirements(id) ON DELETE CASCADE;

--
-- Name: plan_requirement_quotas plan_requirement_quotas_requirement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_quotas
    ADD CONSTRAINT plan_requirement_quotas_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.plan_requirements(id) ON DELETE CASCADE;

--
-- Name: plan_requirement_quotas plan_requirement_quotas_tier_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_quotas
    ADD CONSTRAINT plan_requirement_quotas_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.plan_tiers(id) ON DELETE CASCADE;

--
-- Name: plan_requirements plan_requirements_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirements
    ADD CONSTRAINT plan_requirements_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id) ON DELETE CASCADE;

--
-- Name: plan_tasks plan_tasks_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tasks
    ADD CONSTRAINT plan_tasks_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id) ON DELETE CASCADE;

--
-- Name: plan_tasks plan_tasks_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tasks
    ADD CONSTRAINT plan_tasks_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: plan_tiers plan_tiers_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tiers
    ADD CONSTRAINT plan_tiers_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id) ON DELETE CASCADE;

--
-- Name: plans plans_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
