-- Generated by `just api-schema`. Do not edit: change the database with a migration.

-- Name: plan_levels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_levels (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    period text NOT NULL,
    "position" double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plan_levels_period_check CHECK ((period = ANY (ARRAY['day'::text, 'week'::text, 'month'::text, 'quarter'::text, 'year'::text])))
);

--
-- Name: plan_requirement_habits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_requirement_habits (
    requirement_id uuid NOT NULL,
    habit_id uuid NOT NULL
);

--
-- Name: plan_requirements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_requirements (
    id uuid NOT NULL,
    level_id uuid NOT NULL,
    name text,
    quota double precision NOT NULL,
    measure text DEFAULT 'amount'::text NOT NULL,
    "position" double precision NOT NULL,
    CONSTRAINT plan_requirements_measure_check CHECK ((measure = ANY (ARRAY['amount'::text, 'occurrences'::text]))),
    CONSTRAINT plan_requirements_quota_check CHECK ((quota > (0)::double precision))
);

--
-- Name: plan_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_tasks (
    level_id uuid NOT NULL,
    task_id uuid NOT NULL,
    period_start date NOT NULL
);

--
-- Name: plan_levels plan_levels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_levels
    ADD CONSTRAINT plan_levels_pkey PRIMARY KEY (id);

--
-- Name: plan_levels plan_levels_user_id_period_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_levels
    ADD CONSTRAINT plan_levels_user_id_period_name_key UNIQUE (user_id, period, name);

--
-- Name: plan_requirement_habits plan_requirement_habits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_habits
    ADD CONSTRAINT plan_requirement_habits_pkey PRIMARY KEY (requirement_id, habit_id);

--
-- Name: plan_requirements plan_requirements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirements
    ADD CONSTRAINT plan_requirements_pkey PRIMARY KEY (id);

--
-- Name: plan_tasks plan_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tasks
    ADD CONSTRAINT plan_tasks_pkey PRIMARY KEY (level_id, task_id, period_start);

--
-- Name: idx_plan_levels_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_levels_user ON public.plan_levels USING btree (user_id);

--
-- Name: idx_plan_requirement_habits_habit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_requirement_habits_habit ON public.plan_requirement_habits USING btree (habit_id);

--
-- Name: idx_plan_requirements_level; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_requirements_level ON public.plan_requirements USING btree (level_id);

--
-- Name: idx_plan_tasks_task; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_tasks_task ON public.plan_tasks USING btree (task_id);

--
-- Name: plan_levels set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.plan_levels FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: plan_levels plan_levels_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_levels
    ADD CONSTRAINT plan_levels_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: plan_requirement_habits plan_requirement_habits_habit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_habits
    ADD CONSTRAINT plan_requirement_habits_habit_id_fkey FOREIGN KEY (habit_id) REFERENCES public.habits(id) ON DELETE CASCADE;

--
-- Name: plan_requirement_habits plan_requirement_habits_requirement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirement_habits
    ADD CONSTRAINT plan_requirement_habits_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.plan_requirements(id) ON DELETE CASCADE;

--
-- Name: plan_requirements plan_requirements_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_requirements
    ADD CONSTRAINT plan_requirements_level_id_fkey FOREIGN KEY (level_id) REFERENCES public.plan_levels(id) ON DELETE CASCADE;

--
-- Name: plan_tasks plan_tasks_level_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tasks
    ADD CONSTRAINT plan_tasks_level_id_fkey FOREIGN KEY (level_id) REFERENCES public.plan_levels(id) ON DELETE CASCADE;

--
-- Name: plan_tasks plan_tasks_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_tasks
    ADD CONSTRAINT plan_tasks_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;
