-- Generated by `just api-schema`. Do not edit: change the database with a migration.

-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id uuid NOT NULL,
    task_id uuid NOT NULL,
    author_id uuid NOT NULL,
    parent_id uuid,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    edited_at timestamp with time zone
);

--
-- Name: horizons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.horizons (
    id uuid NOT NULL,
    user_id uuid,
    name text NOT NULL,
    valid_days integer,
    "position" double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT horizons_valid_days_check CHECK (((valid_days IS NULL) OR (valid_days > 0)))
);

--
-- Name: task_labels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_labels (
    task_id uuid NOT NULL,
    label_id uuid NOT NULL
);

--
-- Name: task_relations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_relations (
    from_task_id uuid NOT NULL,
    to_task_id uuid NOT NULL,
    kind text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT task_relations_check CHECK ((from_task_id <> to_task_id))
);

--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    id uuid NOT NULL,
    team_id uuid,
    seq integer,
    creator_id uuid NOT NULL,
    assignee_id uuid,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    state_id uuid NOT NULL,
    priority smallint DEFAULT 0 NOT NULL,
    estimate double precision,
    parent_id uuid,
    project_id uuid,
    milestone_id uuid,
    cycle_id uuid,
    is_milestone_goal boolean DEFAULT false NOT NULL,
    horizon_id uuid,
    horizon_set_at timestamp with time zone,
    due_date date,
    "position" double precision NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    canceled_at timestamp with time zone,
    CONSTRAINT horizon_needs_timestamp CHECK (((horizon_id IS NULL) OR (horizon_set_at IS NOT NULL))),
    CONSTRAINT milestone_goal_needs_milestone CHECK (((is_milestone_goal = false) OR (milestone_id IS NOT NULL))),
    CONSTRAINT seq_belongs_to_team CHECK (((team_id IS NULL) = (seq IS NULL))),
    CONSTRAINT tasks_priority_check CHECK (((priority >= 0) AND (priority <= 4)))
);

--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

--
-- Name: horizons horizons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.horizons
    ADD CONSTRAINT horizons_pkey PRIMARY KEY (id);

--
-- Name: task_labels task_labels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_labels
    ADD CONSTRAINT task_labels_pkey PRIMARY KEY (task_id, label_id);

--
-- Name: task_relations task_relations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_relations
    ADD CONSTRAINT task_relations_pkey PRIMARY KEY (from_task_id, to_task_id, kind);

--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

--
-- Name: idx_comments_author; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_author ON public.comments USING btree (author_id);

--
-- Name: idx_comments_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_parent ON public.comments USING btree (parent_id);

--
-- Name: idx_comments_task; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_task ON public.comments USING btree (task_id);

--
-- Name: idx_horizons_builtin_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_horizons_builtin_name ON public.horizons USING btree (name) WHERE (user_id IS NULL);

--
-- Name: idx_horizons_user_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_horizons_user_name ON public.horizons USING btree (user_id, name) WHERE (user_id IS NOT NULL);

--
-- Name: idx_task_labels_label; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_labels_label ON public.task_labels USING btree (label_id);

--
-- Name: idx_task_relations_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_relations_to ON public.task_relations USING btree (to_task_id);

--
-- Name: idx_tasks_assignee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_assignee ON public.tasks USING btree (assignee_id);

--
-- Name: idx_tasks_creator; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_creator ON public.tasks USING btree (creator_id);

--
-- Name: idx_tasks_cycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_cycle ON public.tasks USING btree (cycle_id);

--
-- Name: idx_tasks_horizon; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_horizon ON public.tasks USING btree (horizon_id);

--
-- Name: idx_tasks_milestone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_milestone ON public.tasks USING btree (milestone_id);

--
-- Name: idx_tasks_milestone_goal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_tasks_milestone_goal ON public.tasks USING btree (milestone_id) WHERE is_milestone_goal;

--
-- Name: idx_tasks_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_parent ON public.tasks USING btree (parent_id);

--
-- Name: idx_tasks_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_project ON public.tasks USING btree (project_id);

--
-- Name: idx_tasks_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_state ON public.tasks USING btree (state_id);

--
-- Name: idx_tasks_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tasks_team ON public.tasks USING btree (team_id);

--
-- Name: idx_tasks_team_seq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_tasks_team_seq ON public.tasks USING btree (team_id, seq) WHERE (team_id IS NOT NULL);

--
-- Name: comments set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: horizons set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.horizons FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: tasks set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.diesel_set_updated_at();

--
-- Name: comments comments_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: comments comments_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE;

--
-- Name: comments comments_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: horizons horizons_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.horizons
    ADD CONSTRAINT horizons_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: task_labels task_labels_label_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_labels
    ADD CONSTRAINT task_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES public.labels(id) ON DELETE CASCADE;

--
-- Name: task_labels task_labels_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_labels
    ADD CONSTRAINT task_labels_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: task_relations task_relations_from_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_relations
    ADD CONSTRAINT task_relations_from_task_id_fkey FOREIGN KEY (from_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: task_relations task_relations_to_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_relations
    ADD CONSTRAINT task_relations_to_task_id_fkey FOREIGN KEY (to_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: tasks tasks_assignee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.users(id) ON DELETE SET NULL;

--
-- Name: tasks tasks_creator_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.users(id) ON DELETE CASCADE;

--
-- Name: tasks tasks_cycle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES public.cycles(id) ON DELETE SET NULL;

--
-- Name: tasks tasks_horizon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_horizon_id_fkey FOREIGN KEY (horizon_id) REFERENCES public.horizons(id) ON DELETE SET NULL;

--
-- Name: tasks tasks_milestone_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.milestones(id) ON DELETE SET NULL;

--
-- Name: tasks tasks_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.tasks(id) ON DELETE SET NULL;

--
-- Name: tasks tasks_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;

--
-- Name: tasks tasks_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.workflow_states(id);

--
-- Name: tasks tasks_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;
